//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prj_BIZ_System.LanguageResource {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class User {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal User() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("prj_BIZ_System.LanguageResource.User", typeof(User).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 500萬以下 的當地語系化字串。
        /// </summary>
        public static string lb_0_5000k {
            get {
                return ResourceManager.GetString("lb_0_5000k", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 1001-1500萬 的當地語系化字串。
        /// </summary>
        public static string lb_10001_15000k {
            get {
                return ResourceManager.GetString("lb_10001_15000k", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 千元 的當地語系化字串。
        /// </summary>
        public static string lb_1000dollars {
            get {
                return ResourceManager.GetString("lb_1000dollars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 1501-3000萬 的當地語系化字串。
        /// </summary>
        public static string lb_15001k_30000k {
            get {
                return ResourceManager.GetString("lb_15001k_30000k", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 3001-5000萬 的當地語系化字串。
        /// </summary>
        public static string lb_30001k_50000k {
            get {
                return ResourceManager.GetString("lb_30001k_50000k", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 三百字以內 的當地語系化字串。
        /// </summary>
        public static string lb_300less {
            get {
                return ResourceManager.GetString("lb_300less", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 5000萬-1億 的當地語系化字串。
        /// </summary>
        public static string lb_50001k_100000k {
            get {
                return ResourceManager.GetString("lb_50001k_100000k", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 501-1000萬 的當地語系化字串。
        /// </summary>
        public static string lb_5001k_10000k {
            get {
                return ResourceManager.GetString("lb_5001k_10000k", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 關於我們 的當地語系化字串。
        /// </summary>
        public static string lb_aboutus {
            get {
                return ResourceManager.GetString("lb_aboutus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 您的會員帳號已成功開通，請於首頁登入使用，謝謝。 的當地語系化字串。
        /// </summary>
        public static string lb_account_activated {
            get {
                return ResourceManager.GetString("lb_account_activated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 帳號管理 的當地語系化字串。
        /// </summary>
        public static string lb_account_info {
            get {
                return ResourceManager.GetString("lb_account_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 帳號不能為空白!! 的當地語系化字串。
        /// </summary>
        public static string lb_account_is_empty {
            get {
                return ResourceManager.GetString("lb_account_is_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 帳號或密碼不能為空白!! 的當地語系化字串。
        /// </summary>
        public static string lb_accountpw_empty {
            get {
                return ResourceManager.GetString("lb_accountpw_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 帳號或密碼錯誤!! 的當地語系化字串。
        /// </summary>
        public static string lb_accountpw_wrong {
            get {
                return ResourceManager.GetString("lb_accountpw_wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 已結束的活動 的當地語系化字串。
        /// </summary>
        public static string lb_acted {
            get {
                return ResourceManager.GetString("lb_acted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 進行中的活動 的當地語系化字串。
        /// </summary>
        public static string lb_acting {
            get {
                return ResourceManager.GetString("lb_acting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 活動 的當地語系化字串。
        /// </summary>
        public static string lb_activities {
            get {
                return ResourceManager.GetString("lb_activities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 與會人數 的當地語系化字串。
        /// </summary>
        public static string lb_activity_amount {
            get {
                return ResourceManager.GetString("lb_activity_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 活動日期 的當地語系化字串。
        /// </summary>
        public static string lb_activity_date {
            get {
                return ResourceManager.GetString("lb_activity_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 活動名稱 的當地語系化字串。
        /// </summary>
        public static string lb_activity_name {
            get {
                return ResourceManager.GetString("lb_activity_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 活動編號 的當地語系化字串。
        /// </summary>
        public static string lb_activity_no {
            get {
                return ResourceManager.GetString("lb_activity_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 與會人 的當地語系化字串。
        /// </summary>
        public static string lb_activity_participant {
            get {
                return ResourceManager.GetString("lb_activity_participant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 活動期間 的當地語系化字串。
        /// </summary>
        public static string lb_activity_period {
            get {
                return ResourceManager.GetString("lb_activity_period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新北市ICT國際對接 的當地語系化字串。
        /// </summary>
        public static string lb_activity_photo1 {
            get {
                return ResourceManager.GetString("lb_activity_photo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新北市4G而動-快速作業平臺 的當地語系化字串。
        /// </summary>
        public static string lb_activity_photo2 {
            get {
                return ResourceManager.GetString("lb_activity_photo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新北市機械及金屬產業高值化拓展會 的當地語系化字串。
        /// </summary>
        public static string lb_activity_photo3 {
            get {
                return ResourceManager.GetString("lb_activity_photo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 活動報名 的當地語系化字串。
        /// </summary>
        public static string lb_activity_register {
            get {
                return ResourceManager.GetString("lb_activity_register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 活動地點 的當地語系化字串。
        /// </summary>
        public static string lb_activity_site {
            get {
                return ResourceManager.GetString("lb_activity_site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 活動相關資訊 的當地語系化字串。
        /// </summary>
        public static string lb_activityinfo {
            get {
                return ResourceManager.GetString("lb_activityinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 活動列表 的當地語系化字串。
        /// </summary>
        public static string lb_activitylist {
            get {
                return ResourceManager.GetString("lb_activitylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 活動照片 的當地語系化字串。
        /// </summary>
        public static string lb_activitypic {
            get {
                return ResourceManager.GetString("lb_activitypic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 活動註冊資訊 的當地語系化字串。
        /// </summary>
        public static string lb_activityregister {
            get {
                return ResourceManager.GetString("lb_activityregister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 活動類型 的當地語系化字串。
        /// </summary>
        public static string lb_activitytype {
            get {
                return ResourceManager.GetString("lb_activitytype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新增 的當地語系化字串。
        /// </summary>
        public static string lb_add {
            get {
                return ResourceManager.GetString("lb_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新增失敗 的當地語系化字串。
        /// </summary>
        public static string lb_add_fail {
            get {
                return ResourceManager.GetString("lb_add_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新增成功 的當地語系化字串。
        /// </summary>
        public static string lb_add_successful {
            get {
                return ResourceManager.GetString("lb_add_successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 地址 的當地語系化字串。
        /// </summary>
        public static string lb_addr {
            get {
                return ResourceManager.GetString("lb_addr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 上傳影音型錄 的當地語系化字串。
        /// </summary>
        public static string lb_addvideo {
            get {
                return ResourceManager.GetString("lb_addvideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 資本額 的當地語系化字串。
        /// </summary>
        public static string lb_amountofcapital {
            get {
                return ResourceManager.GetString("lb_amountofcapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 回覆數 的當地語系化字串。
        /// </summary>
        public static string lb_amountofreply {
            get {
                return ResourceManager.GetString("lb_amountofreply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 與會人數不可為空白 的當地語系化字串。
        /// </summary>
        public static string lb_amountparticipant_is_empty {
            get {
                return ResourceManager.GetString("lb_amountparticipant_is_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 APP下載 的當地語系化字串。
        /// </summary>
        public static string lb_appdownload {
            get {
                return ResourceManager.GetString("lb_appdownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 附件 的當地語系化字串。
        /// </summary>
        public static string lb_attachment {
            get {
                return ResourceManager.GetString("lb_attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 上傳附件 的當地語系化字串。
        /// </summary>
        public static string lb_attachment_upload {
            get {
                return ResourceManager.GetString("lb_attachment_upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 已完成審核 的當地語系化字串。
        /// </summary>
        public static string lb_audited {
            get {
                return ResourceManager.GetString("lb_audited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 發布人 的當地語系化字串。
        /// </summary>
        public static string lb_author {
            get {
                return ResourceManager.GetString("lb_author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 返回 的當地語系化字串。
        /// </summary>
        public static string lb_back {
            get {
                return ResourceManager.GetString("lb_back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 回產品列表 的當地語系化字串。
        /// </summary>
        public static string lb_back_pdlist {
            get {
                return ResourceManager.GetString("lb_back_pdlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 回首頁 的當地語系化字串。
        /// </summary>
        public static string lb_backhome {
            get {
                return ResourceManager.GetString("lb_backhome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 您好，請先登入會員再報名活動，是否回首頁登入? 的當地語系化字串。
        /// </summary>
        public static string lb_backlogin_a {
            get {
                return ResourceManager.GetString("lb_backlogin_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 您好，請先登入會員再傳送訊息，是否回首頁登入? 的當地語系化字串。
        /// </summary>
        public static string lb_backlogin_m {
            get {
                return ResourceManager.GetString("lb_backlogin_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 商務媒合需求 的當地語系化字串。
        /// </summary>
        public static string lb_biz_requirement {
            get {
                return ResourceManager.GetString("lb_biz_requirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 會議/論壇 的當地語系化字串。
        /// </summary>
        public static string lb_bizexploremisson {
            get {
                return ResourceManager.GetString("lb_bizexploremisson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 代表人 的當地語系化字串。
        /// </summary>
        public static string lb_boss {
            get {
                return ResourceManager.GetString("lb_boss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 買家 的當地語系化字串。
        /// </summary>
        public static string lb_buyer {
            get {
                return ResourceManager.GetString("lb_buyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 您表達有意願洽談的買家 的當地語系化字串。
        /// </summary>
        public static string lb_buyer_chosen {
            get {
                return ResourceManager.GetString("lb_buyer_chosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 已排定洽談的買家 的當地語系化字串。
        /// </summary>
        public static string lb_buyer_matched {
            get {
                return ResourceManager.GetString("lb_buyer_matched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 買方專區 的當地語系化字串。
        /// </summary>
        public static string lb_buyerarea {
            get {
                return ResourceManager.GetString("lb_buyerarea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 買主帳號 的當地語系化字串。
        /// </summary>
        public static string lb_buyerid {
            get {
                return ResourceManager.GetString("lb_buyerid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 買主資訊 的當地語系化字串。
        /// </summary>
        public static string lb_buyerinfo {
            get {
                return ResourceManager.GetString("lb_buyerinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 買主資訊列表 的當地語系化字串。
        /// </summary>
        public static string lb_buyerlist {
            get {
                return ResourceManager.GetString("lb_buyerlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 買主媒合需求 的當地語系化字串。
        /// </summary>
        public static string lb_buyerneed {
            get {
                return ResourceManager.GetString("lb_buyerneed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 取消報名 的當地語系化字串。
        /// </summary>
        public static string lb_cancel {
            get {
                return ResourceManager.GetString("lb_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 型錄名稱不可為空白 的當地語系化字串。
        /// </summary>
        public static string lb_catalog_is_empty {
            get {
                return ResourceManager.GetString("lb_catalog_is_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 型錄名稱 的當地語系化字串。
        /// </summary>
        public static string lb_catalogname {
            get {
                return ResourceManager.GetString("lb_catalogname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 上傳型錄 的當地語系化字串。
        /// </summary>
        public static string lb_catalogupload {
            get {
                return ResourceManager.GetString("lb_catalogupload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 企業類型 的當地語系化字串。
        /// </summary>
        public static string lb_category {
            get {
                return ResourceManager.GetString("lb_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 手機號碼不可為空白 的當地語系化字串。
        /// </summary>
        public static string lb_celeno_is_empty {
            get {
                return ResourceManager.GetString("lb_celeno_is_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 修改密碼 的當地語系化字串。
        /// </summary>
        public static string lb_changepw {
            get {
                return ResourceManager.GetString("lb_changepw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 是否修改洽談對象 的當地語系化字串。
        /// </summary>
        public static string lb_changeselect {
            get {
                return ResourceManager.GetString("lb_changeselect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請勾選 的當地語系化字串。
        /// </summary>
        public static string lb_check {
            get {
                return ResourceManager.GetString("lb_check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確認新密碼 的當地語系化字串。
        /// </summary>
        public static string lb_checknewpw {
            get {
                return ResourceManager.GetString("lb_checknewpw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 很抱歉!請點選正確的訊息連結 的當地語系化字串。
        /// </summary>
        public static string lb_click_correct {
            get {
                return ResourceManager.GetString("lb_click_correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請點擊右上按鈕選擇會員身份 的當地語系化字串。
        /// </summary>
        public static string lb_click_member {
            get {
                return ResourceManager.GetString("lb_click_member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 產業聚落 的當地語系化字串。
        /// </summary>
        public static string lb_cluster {
            get {
                return ResourceManager.GetString("lb_cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 關於聚落 的當地語系化字串。
        /// </summary>
        public static string lb_cluster_about {
            get {
                return ResourceManager.GetString("lb_cluster_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 聚落簡介 的當地語系化字串。
        /// </summary>
        public static string lb_cluster_brief {
            get {
                return ResourceManager.GetString("lb_cluster_brief", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 成立時間 的當地語系化字串。
        /// </summary>
        public static string lb_cluster_create {
            get {
                return ResourceManager.GetString("lb_cluster_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 聚落文件 的當地語系化字串。
        /// </summary>
        public static string lb_cluster_doc {
            get {
                return ResourceManager.GetString("lb_cluster_doc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 進入聚落 的當地語系化字串。
        /// </summary>
        public static string lb_cluster_enter {
            get {
                return ResourceManager.GetString("lb_cluster_enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 聚落邀請 的當地語系化字串。
        /// </summary>
        public static string lb_cluster_invite {
            get {
                return ResourceManager.GetString("lb_cluster_invite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 申請加入聚落 的當地語系化字串。
        /// </summary>
        public static string lb_cluster_join {
            get {
                return ResourceManager.GetString("lb_cluster_join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 退出聚落 的當地語系化字串。
        /// </summary>
        public static string lb_cluster_leave {
            get {
                return ResourceManager.GetString("lb_cluster_leave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 產業聚落列表 的當地語系化字串。
        /// </summary>
        public static string lb_cluster_list {
            get {
                return ResourceManager.GetString("lb_cluster_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 管理者 的當地語系化字串。
        /// </summary>
        public static string lb_cluster_manager {
            get {
                return ResourceManager.GetString("lb_cluster_manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 聚落商家 的當地語系化字串。
        /// </summary>
        public static string lb_cluster_member {
            get {
                return ResourceManager.GetString("lb_cluster_member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 聚落名稱 的當地語系化字串。
        /// </summary>
        public static string lb_cluster_name {
            get {
                return ResourceManager.GetString("lb_cluster_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 邀請中成員 的當地語系化字串。
        /// </summary>
        public static string lb_cluster_pending {
            get {
                return ResourceManager.GetString("lb_cluster_pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 上傳文件 的當地語系化字串。
        /// </summary>
        public static string lb_cluster_upload {
            get {
                return ResourceManager.GetString("lb_cluster_upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 企 的當地語系化字串。
        /// </summary>
        public static string lb_co {
            get {
                return ResourceManager.GetString("lb_co", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 企業會員 的當地語系化字串。
        /// </summary>
        public static string lb_co_member {
            get {
                return ResourceManager.GetString("lb_co_member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 企業資料庫 的當地語系化字串。
        /// </summary>
        public static string lb_company {
            get {
                return ResourceManager.GetString("lb_company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 公司型錄 的當地語系化字串。
        /// </summary>
        public static string lb_company_catalog {
            get {
                return ResourceManager.GetString("lb_company_catalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 企業簡介 的當地語系化字串。
        /// </summary>
        public static string lb_companybrief {
            get {
                return ResourceManager.GetString("lb_companybrief", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 統一編號 的當地語系化字串。
        /// </summary>
        public static string lb_companyid {
            get {
                return ResourceManager.GetString("lb_companyid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 公司名稱 的當地語系化字串。
        /// </summary>
        public static string lb_companyname {
            get {
                return ResourceManager.GetString("lb_companyname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請輸入確認密碼欄位!! 的當地語系化字串。
        /// </summary>
        public static string lb_confirmpw_is_empty {
            get {
                return ResourceManager.GetString("lb_confirmpw_is_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 想與買家洽談 的當地語系化字串。
        /// </summary>
        public static string lb_consult2buyer {
            get {
                return ResourceManager.GetString("lb_consult2buyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 想與賣家洽談 的當地語系化字串。
        /// </summary>
        public static string lb_consult2seller {
            get {
                return ResourceManager.GetString("lb_consult2seller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 主聯絡人不可為空白 的當地語系化字串。
        /// </summary>
        public static string lb_contact_is_empty {
            get {
                return ResourceManager.GetString("lb_contact_is_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 主聯絡人 的當地語系化字串。
        /// </summary>
        public static string lb_contactman {
            get {
                return ResourceManager.GetString("lb_contactman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 聯絡人姓名 的當地語系化字串。
        /// </summary>
        public static string lb_contactname {
            get {
                return ResourceManager.GetString("lb_contactname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 聯絡我們 的當地語系化字串。
        /// </summary>
        public static string lb_contactus {
            get {
                return ResourceManager.GetString("lb_contactus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 版權所有 的當地語系化字串。
        /// </summary>
        public static string lb_copyright {
            get {
                return ResourceManager.GetString("lb_copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 採購範圍 的當地語系化字串。
        /// </summary>
        public static string lb_coverage {
            get {
                return ResourceManager.GetString("lb_coverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 上傳封面 的當地語系化字串。
        /// </summary>
        public static string lb_coverupload {
            get {
                return ResourceManager.GetString("lb_coverupload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請自訂帳號 的當地語系化字串。
        /// </summary>
        public static string lb_create_account {
            get {
                return ResourceManager.GetString("lb_create_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新建活動 的當地語系化字串。
        /// </summary>
        public static string lb_create_activity {
            get {
                return ResourceManager.GetString("lb_create_activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 輸入的資料不正確，請重新操作!! 的當地語系化字串。
        /// </summary>
        public static string lb_data_wrong {
            get {
                return ResourceManager.GetString("lb_data_wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 發佈日期 的當地語系化字串。
        /// </summary>
        public static string lb_date {
            get {
                return ResourceManager.GetString("lb_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 刪除 的當地語系化字串。
        /// </summary>
        public static string lb_delete {
            get {
                return ResourceManager.GetString("lb_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 刪除失敗 的當地語系化字串。
        /// </summary>
        public static string lb_delete_fail {
            get {
                return ResourceManager.GetString("lb_delete_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 刪除成功 的當地語系化字串。
        /// </summary>
        public static string lb_delete_successful {
            get {
                return ResourceManager.GetString("lb_delete_successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 是否確認要刪除? 的當地語系化字串。
        /// </summary>
        public static string lb_deleteornot {
            get {
                return ResourceManager.GetString("lb_deleteornot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 內容 的當地語系化字串。
        /// </summary>
        public static string lb_detail {
            get {
                return ResourceManager.GetString("lb_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 國內企業 的當地語系化字串。
        /// </summary>
        public static string lb_domestic {
            get {
                return ResourceManager.GetString("lb_domestic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 下載 的當地語系化字串。
        /// </summary>
        public static string lb_download {
            get {
                return ResourceManager.GetString("lb_download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 修改 的當地語系化字串。
        /// </summary>
        public static string lb_edit {
            get {
                return ResourceManager.GetString("lb_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 電子郵件 的當地語系化字串。
        /// </summary>
        public static string lb_email {
            get {
                return ResourceManager.GetString("lb_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 電子郵件不可為空白 的當地語系化字串。
        /// </summary>
        public static string lb_email_is_empty {
            get {
                return ResourceManager.GetString("lb_email_is_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 英文資訊 的當地語系化字串。
        /// </summary>
        public static string lb_en_info {
            get {
                return ResourceManager.GetString("lb_en_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 業績預估表 的當地語系化字串。
        /// </summary>
        public static string lb_estimate {
            get {
                return ResourceManager.GetString("lb_estimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 預估採購金額(USD) 的當地語系化字串。
        /// </summary>
        public static string lb_estimated_amount {
            get {
                return ResourceManager.GetString("lb_estimated_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 說明 的當地語系化字串。
        /// </summary>
        public static string lb_explain {
            get {
                return ResourceManager.GetString("lb_explain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 常見問題 的當地語系化字串。
        /// </summary>
        public static string lb_faqs {
            get {
                return ResourceManager.GetString("lb_faqs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 檔案名稱 的當地語系化字串。
        /// </summary>
        public static string lb_filename {
            get {
                return ResourceManager.GetString("lb_filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 檔案大小 的當地語系化字串。
        /// </summary>
        public static string lb_filesize {
            get {
                return ResourceManager.GetString("lb_filesize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 外國企業 的當地語系化字串。
        /// </summary>
        public static string lb_foreign {
            get {
                return ResourceManager.GetString("lb_foreign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 忘記密碼 的當地語系化字串。
        /// </summary>
        public static string lb_forget_pw {
            get {
                return ResourceManager.GetString("lb_forget_pw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 公開討論區 的當地語系化字串。
        /// </summary>
        public static string lb_forum {
            get {
                return ResourceManager.GetString("lb_forum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 推薦活動 的當地語系化字串。
        /// </summary>
        public static string lb_good_activities {
            get {
                return ResourceManager.GetString("lb_good_activities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 政府/公協會 的當地語系化字串。
        /// </summary>
        public static string lb_gov {
            get {
                return ResourceManager.GetString("lb_gov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 您好，歡迎您成為會員! 的當地語系化字串。
        /// </summary>
        public static string lb_hello {
            get {
                return ResourceManager.GetString("lb_hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 首頁 的當地語系化字串。
        /// </summary>
        public static string lb_home {
            get {
                return ResourceManager.GetString("lb_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 編號 的當地語系化字串。
        /// </summary>
        public static string lb_id {
            get {
                return ResourceManager.GetString("lb_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 該使用帳號已存在,請確認是否帳號有誤!! 的當地語系化字串。
        /// </summary>
        public static string lb_id_alreadyexist {
            get {
                return ResourceManager.GetString("lb_id_alreadyexist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 國內企業帳號請用統一編號註冊 的當地語系化字串。
        /// </summary>
        public static string lb_iduse_companyid {
            get {
                return ResourceManager.GetString("lb_iduse_companyid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 若您忘記密碼，請輸入註冊時的帳號及Email，系統將送一組預設密碼給您，如有疑問，請洽系統管理人員，謝謝。 的當地語系化字串。
        /// </summary>
        public static string lb_ifforgetpw {
            get {
                return ResourceManager.GetString("lb_ifforgetpw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 我已詳閱並同意服務條款及隱私政策內容，並同意平台公開貴司所提供之公示資訊。 的當地語系化字串。
        /// </summary>
        public static string lb_ihaveagree {
            get {
                return ResourceManager.GetString("lb_ihaveagree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 企業資料說明 的當地語系化字串。
        /// </summary>
        public static string lb_info {
            get {
                return ResourceManager.GetString("lb_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 是否公開 的當地語系化字串。
        /// </summary>
        public static string lb_is_public {
            get {
                return ResourceManager.GetString("lb_is_public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 不公開 的當地語系化字串。
        /// </summary>
        public static string lb_is_public_no {
            get {
                return ResourceManager.GetString("lb_is_public_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 公開 的當地語系化字串。
        /// </summary>
        public static string lb_is_public_yes {
            get {
                return ResourceManager.GetString("lb_is_public_yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 採購項目 的當地語系化字串。
        /// </summary>
        public static string lb_items {
            get {
                return ResourceManager.GetString("lb_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 最新活動 的當地語系化字串。
        /// </summary>
        public static string lb_latest_activity {
            get {
                return ResourceManager.GetString("lb_latest_activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 最新消息 的當地語系化字串。
        /// </summary>
        public static string lb_latest_activitynews {
            get {
                return ResourceManager.GetString("lb_latest_activitynews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 最新上架企業 的當地語系化字串。
        /// </summary>
        public static string lb_latest_company {
            get {
                return ResourceManager.GetString("lb_latest_company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 最新新聞 的當地語系化字串。
        /// </summary>
        public static string lb_latest_news {
            get {
                return ResourceManager.GetString("lb_latest_news", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 最新影音型錄 的當地語系化字串。
        /// </summary>
        public static string lb_latest_video {
            get {
                return ResourceManager.GetString("lb_latest_video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 最新型錄 的當地語系化字串。
        /// </summary>
        public static string lb_latestcatalog {
            get {
                return ResourceManager.GetString("lb_latestcatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 相關資訊連結 的當地語系化字串。
        /// </summary>
        public static string lb_link {
            get {
                return ResourceManager.GetString("lb_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 列表 的當地語系化字串。
        /// </summary>
        public static string lb_list {
            get {
                return ResourceManager.GetString("lb_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 會員登入 的當地語系化字串。
        /// </summary>
        public static string lb_login {
            get {
                return ResourceManager.GetString("lb_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 上傳LOGO 的當地語系化字串。
        /// </summary>
        public static string lb_logoupload {
            get {
                return ResourceManager.GetString("lb_logoupload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 登出 的當地語系化字串。
        /// </summary>
        public static string lb_logout {
            get {
                return ResourceManager.GetString("lb_logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 生 的當地語系化字串。
        /// </summary>
        public static string lb_manu {
            get {
                return ResourceManager.GetString("lb_manu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 生產會員 的當地語系化字串。
        /// </summary>
        public static string lb_manu_member {
            get {
                return ResourceManager.GetString("lb_manu_member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 操作手冊 的當地語系化字串。
        /// </summary>
        public static string lb_manual {
            get {
                return ResourceManager.GetString("lb_manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 商務媒合 的當地語系化字串。
        /// </summary>
        public static string lb_matchmaking {
            get {
                return ResourceManager.GetString("lb_matchmaking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 商家管理 的當地語系化字串。
        /// </summary>
        public static string lb_member_management {
            get {
                return ResourceManager.GetString("lb_member_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 您已驗證過本會員帳號，請於首頁登入使用，謝謝。 的當地語系化字串。
        /// </summary>
        public static string lb_member_verified {
            get {
                return ResourceManager.GetString("lb_member_verified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 會員驗證 的當地語系化字串。
        /// </summary>
        public static string lb_memberok {
            get {
                return ResourceManager.GetString("lb_memberok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 因廠商報名仍在進行，所以媒合功能尚未開放。廠商名單底定後系統將以email形式通知您進行媒合，謝謝! 的當地語系化字串。
        /// </summary>
        public static string lb_mm_notopen {
            get {
                return ResourceManager.GetString("lb_mm_notopen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 媒合結果 的當地語系化字串。
        /// </summary>
        public static string lb_mm_result {
            get {
                return ResourceManager.GetString("lb_mm_result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 一億以上 的當地語系化字串。
        /// </summary>
        public static string lb_morethan100000k {
            get {
                return ResourceManager.GetString("lb_morethan100000k", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 訊息 的當地語系化字串。
        /// </summary>
        public static string lb_msg {
            get {
                return ResourceManager.GetString("lb_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 訊息不能超過三百字 的當地語系化字串。
        /// </summary>
        public static string lb_msg_300 {
            get {
                return ResourceManager.GetString("lb_msg_300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 聚落訊息 的當地語系化字串。
        /// </summary>
        public static string lb_msg_cluster {
            get {
                return ResourceManager.GetString("lb_msg_cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 公司訊息 的當地語系化字串。
        /// </summary>
        public static string lb_msg_company {
            get {
                return ResourceManager.GetString("lb_msg_company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 訊息內容不能為空白 的當地語系化字串。
        /// </summary>
        public static string lb_msg_empty {
            get {
                return ResourceManager.GetString("lb_msg_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 很抱歉!您沒有觀看這則訊息的權限 的當地語系化字串。
        /// </summary>
        public static string lb_msg_limit {
            get {
                return ResourceManager.GetString("lb_msg_limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 訊息管理 的當地語系化字串。
        /// </summary>
        public static string lb_msg_managment {
            get {
                return ResourceManager.GetString("lb_msg_managment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 私人訊息 的當地語系化字串。
        /// </summary>
        public static string lb_msg_private {
            get {
                return ResourceManager.GetString("lb_msg_private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 可複選 的當地語系化字串。
        /// </summary>
        public static string lb_multiple {
            get {
                return ResourceManager.GetString("lb_multiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 必須為 的當地語系化字串。
        /// </summary>
        public static string lb_must {
            get {
                return ResourceManager.GetString("lb_must", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 我的 的當地語系化字串。
        /// </summary>
        public static string lb_my {
            get {
                return ResourceManager.GetString("lb_my", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 我的資料庫 的當地語系化字串。
        /// </summary>
        public static string lb_mycompany {
            get {
                return ResourceManager.GetString("lb_mycompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 我的會員資料 的當地語系化字串。
        /// </summary>
        public static string lb_myinfo {
            get {
                return ResourceManager.GetString("lb_myinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 創建新帳號 的當地語系化字串。
        /// </summary>
        public static string lb_newid {
            get {
                return ResourceManager.GetString("lb_newid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新密碼 的當地語系化字串。
        /// </summary>
        public static string lb_newpw {
            get {
                return ResourceManager.GetString("lb_newpw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新密碼不可為空白 的當地語系化字串。
        /// </summary>
        public static string lb_newpw_is_empty {
            get {
                return ResourceManager.GetString("lb_newpw_is_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新的密碼通知信已寄出，請至你註冊的信箱收取!! 的當地語系化字串。
        /// </summary>
        public static string lb_newpwemail {
            get {
                return ResourceManager.GetString("lb_newpwemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新聞 的當地語系化字串。
        /// </summary>
        public static string lb_news {
            get {
                return ResourceManager.GetString("lb_news", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 否 的當地語系化字串。
        /// </summary>
        public static string lb_no {
            get {
                return ResourceManager.GetString("lb_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 目前沒有推薦的活動 的當地語系化字串。
        /// </summary>
        public static string lb_no_recommended {
            get {
                return ResourceManager.GetString("lb_no_recommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 您尚未參加任何活動 的當地語系化字串。
        /// </summary>
        public static string lb_no_register {
            get {
                return ResourceManager.GetString("lb_no_register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 查無資料!! 的當地語系化字串。
        /// </summary>
        public static string lb_nodata {
            get {
                return ResourceManager.GetString("lb_nodata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 未選擇任何檔案 的當地語系化字串。
        /// </summary>
        public static string lb_nonefile {
            get {
                return ResourceManager.GetString("lb_nonefile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 訊息對象 的當地語系化字串。
        /// </summary>
        public static string lb_object {
            get {
                return ResourceManager.GetString("lb_object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 對象不能為空白 的當地語系化字串。
        /// </summary>
        public static string lb_object_empty {
            get {
                return ResourceManager.GetString("lb_object_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確定 的當地語系化字串。
        /// </summary>
        public static string lb_ok {
            get {
                return ResourceManager.GetString("lb_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 舊密碼不可為空白 的當地語系化字串。
        /// </summary>
        public static string lb_oldpw_is_empty {
            get {
                return ResourceManager.GetString("lb_oldpw_is_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 訂單列表 的當地語系化字串。
        /// </summary>
        public static string lb_order_list {
            get {
                return ResourceManager.GetString("lb_order_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 主辦單位 的當地語系化字串。
        /// </summary>
        public static string lb_organizer {
            get {
                return ResourceManager.GetString("lb_organizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 舊密碼 的當地語系化字串。
        /// </summary>
        public static string lb_originalpw {
            get {
                return ResourceManager.GetString("lb_originalpw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 上傳者 的當地語系化字串。
        /// </summary>
        public static string lb_owner {
            get {
                return ResourceManager.GetString("lb_owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 產品類型 的當地語系化字串。
        /// </summary>
        public static string lb_p_category {
            get {
                return ResourceManager.GetString("lb_p_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 產品資料 的當地語系化字串。
        /// </summary>
        public static string lb_p_info {
            get {
                return ResourceManager.GetString("lb_p_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 產品型號 的當地語系化字串。
        /// </summary>
        public static string lb_p_model {
            get {
                return ResourceManager.GetString("lb_p_model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 產品專利/得獎 的當地語系化字串。
        /// </summary>
        public static string lb_p_patent {
            get {
                return ResourceManager.GetString("lb_p_patent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 產品規格及其他 的當地語系化字串。
        /// </summary>
        public static string lb_p_specification {
            get {
                return ResourceManager.GetString("lb_p_specification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 您的會員驗證參數錯誤，請重發驗證信或聯絡客服人員，謝謝。 的當地語系化字串。
        /// </summary>
        public static string lb_parameter_wrong {
            get {
                return ResourceManager.GetString("lb_parameter_wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 與會人不可為空白 的當地語系化字串。
        /// </summary>
        public static string lb_participant_is_empty {
            get {
                return ResourceManager.GetString("lb_participant_is_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 密碼 的當地語系化字串。
        /// </summary>
        public static string lb_password {
            get {
                return ResourceManager.GetString("lb_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 線上型錄 的當地語系化字串。
        /// </summary>
        public static string lb_pdf {
            get {
                return ResourceManager.GetString("lb_pdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 上傳檔案 的當地語系化字串。
        /// </summary>
        public static string lb_pdfupload {
            get {
                return ResourceManager.GetString("lb_pdfupload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 產品名稱不可為空白 的當地語系化字串。
        /// </summary>
        public static string lb_pdname_is_empty {
            get {
                return ResourceManager.GetString("lb_pdname_is_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 業績管理 的當地語系化字串。
        /// </summary>
        public static string lb_performance {
            get {
                return ResourceManager.GetString("lb_performance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 手機號碼 的當地語系化字串。
        /// </summary>
        public static string lb_phone_no {
            get {
                return ResourceManager.GetString("lb_phone_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 上傳圖片 的當地語系化字串。
        /// </summary>
        public static string lb_photoupload {
            get {
                return ResourceManager.GetString("lb_photoupload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請用統一編號註冊 的當地語系化字串。
        /// </summary>
        public static string lb_pleaseuse_companyid {
            get {
                return ResourceManager.GetString("lb_pleaseuse_companyid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 隱私政策 的當地語系化字串。
        /// </summary>
        public static string lb_privacypolicy {
            get {
                return ResourceManager.GetString("lb_privacypolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 型號 的當地語系化字串。
        /// </summary>
        public static string lb_prod_model_no {
            get {
                return ResourceManager.GetString("lb_prod_model_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 公司產品 的當地語系化字串。
        /// </summary>
        public static string lb_product_company {
            get {
                return ResourceManager.GetString("lb_product_company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請輸入產品英文名稱 的當地語系化字串。
        /// </summary>
        public static string lb_product_en_is_empty {
            get {
                return ResourceManager.GetString("lb_product_en_is_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 產品說明 的當地語系化字串。
        /// </summary>
        public static string lb_product_info {
            get {
                return ResourceManager.GetString("lb_product_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 產品名稱 的當地語系化字串。
        /// </summary>
        public static string lb_product_name {
            get {
                return ResourceManager.GetString("lb_product_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請輸入產品中文名稱 的當地語系化字串。
        /// </summary>
        public static string lb_product_tw_is_empty {
            get {
                return ResourceManager.GetString("lb_product_tw_is_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請輸入產品英文說明 的當地語系化字串。
        /// </summary>
        public static string lb_productbrife_en_is_empty {
            get {
                return ResourceManager.GetString("lb_productbrife_en_is_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請輸入產品中文說明 的當地語系化字串。
        /// </summary>
        public static string lb_productbrife_tw_is_empty {
            get {
                return ResourceManager.GetString("lb_productbrife_tw_is_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 公司簡介 的當地語系化字串。
        /// </summary>
        public static string lb_profile {
            get {
                return ResourceManager.GetString("lb_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 發佈人 的當地語系化字串。
        /// </summary>
        public static string lb_publisher {
            get {
                return ResourceManager.GetString("lb_publisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 密碼不能為空白!! 的當地語系化字串。
        /// </summary>
        public static string lb_pw_is_empty {
            get {
                return ResourceManager.GetString("lb_pw_is_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新的註冊密碼通知信更新失敗，請重新操作!! 的當地語系化字串。
        /// </summary>
        public static string lb_pwmailfail {
            get {
                return ResourceManager.GetString("lb_pwmailfail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 密碼請設8個字元的英文及數字混合 的當地語系化字串。
        /// </summary>
        public static string lb_pwset8 {
            get {
                return ResourceManager.GetString("lb_pwset8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 報價單列表 的當地語系化字串。
        /// </summary>
        public static string lb_quotation_list {
            get {
                return ResourceManager.GetString("lb_quotation_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 已讀 的當地語系化字串。
        /// </summary>
        public static string lb_read {
            get {
                return ResourceManager.GetString("lb_read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確認密碼錯誤,請重新確認密碼是否有誤!! 的當地語系化字串。
        /// </summary>
        public static string lb_reconfirmpw {
            get {
                return ResourceManager.GetString("lb_reconfirmpw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 同上密碼請再次輸入確認 的當地語系化字串。
        /// </summary>
        public static string lb_reenterpw {
            get {
                return ResourceManager.GetString("lb_reenterpw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 報名資料 的當地語系化字串。
        /// </summary>
        public static string lb_registerinfo {
            get {
                return ResourceManager.GetString("lb_registerinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 回覆 的當地語系化字串。
        /// </summary>
        public static string lb_reply {
            get {
                return ResourceManager.GetString("lb_reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 回覆內容不能超過三百字 的當地語系化字串。
        /// </summary>
        public static string lb_reply_300 {
            get {
                return ResourceManager.GetString("lb_reply_300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 回覆內容 的當地語系化字串。
        /// </summary>
        public static string lb_reply_content {
            get {
                return ResourceManager.GetString("lb_reply_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 回覆內容不能為空白 的當地語系化字串。
        /// </summary>
        public static string lb_reply_empty {
            get {
                return ResourceManager.GetString("lb_reply_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 重選檔案 的當地語系化字串。
        /// </summary>
        public static string lb_reselect {
            get {
                return ResourceManager.GetString("lb_reselect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 業 的當地語系化字串。
        /// </summary>
        public static string lb_sa {
            get {
                return ResourceManager.GetString("lb_sa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 業務會員 的當地語系化字串。
        /// </summary>
        public static string lb_sa_member {
            get {
                return ResourceManager.GetString("lb_sa_member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 業務帳號管理 的當地語系化字串。
        /// </summary>
        public static string lb_sales_idlist {
            get {
                return ResourceManager.GetString("lb_sales_idlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 儲存 的當地語系化字串。
        /// </summary>
        public static string lb_save {
            get {
                return ResourceManager.GetString("lb_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 產業別 的當地語系化字串。
        /// </summary>
        public static string lb_scope {
            get {
                return ResourceManager.GetString("lb_scope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請選擇產業別 的當地語系化字串。
        /// </summary>
        public static string lb_scope_sel {
            get {
                return ResourceManager.GetString("lb_scope_sel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 查詢 的當地語系化字串。
        /// </summary>
        public static string lb_search {
            get {
                return ResourceManager.GetString("lb_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請輸入查詢條件 的當地語系化字串。
        /// </summary>
        public static string lb_search_need {
            get {
                return ResourceManager.GetString("lb_search_need", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 查詢結果 的當地語系化字串。
        /// </summary>
        public static string lb_searchresult {
            get {
                return ResourceManager.GetString("lb_searchresult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 選取檔案 的當地語系化字串。
        /// </summary>
        public static string lb_select {
            get {
                return ResourceManager.GetString("lb_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Logo圖片選擇成功 的當地語系化字串。
        /// </summary>
        public static string lb_select_successful {
            get {
                return ResourceManager.GetString("lb_select_successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 賣家 的當地語系化字串。
        /// </summary>
        public static string lb_seller {
            get {
                return ResourceManager.GetString("lb_seller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 您表達有意願洽談的賣家 的當地語系化字串。
        /// </summary>
        public static string lb_seller_chosen {
            get {
                return ResourceManager.GetString("lb_seller_chosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 已排定洽談的賣家 的當地語系化字串。
        /// </summary>
        public static string lb_seller_matched {
            get {
                return ResourceManager.GetString("lb_seller_matched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 賣家帳號 的當地語系化字串。
        /// </summary>
        public static string lb_sellerid {
            get {
                return ResourceManager.GetString("lb_sellerid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 賣家清單 的當地語系化字串。
        /// </summary>
        public static string lb_sellerlist {
            get {
                return ResourceManager.GetString("lb_sellerlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 我們已寄發一封「會員驗證信」至您的註冊信箱 的當地語系化字串。
        /// </summary>
        public static string lb_sendmail {
            get {
                return ResourceManager.GetString("lb_sendmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 發送訊息 的當地語系化字串。
        /// </summary>
        public static string lb_sendmsg {
            get {
                return ResourceManager.GetString("lb_sendmsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 註冊 的當地語系化字串。
        /// </summary>
        public static string lb_signup {
            get {
                return ResourceManager.GetString("lb_signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 我要報名 的當地語系化字串。
        /// </summary>
        public static string lb_signup_me {
            get {
                return ResourceManager.GetString("lb_signup_me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新創團隊 的當地語系化字串。
        /// </summary>
        public static string lb_startup {
            get {
                return ResourceManager.GetString("lb_startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 主題 的當地語系化字串。
        /// </summary>
        public static string lb_subject {
            get {
                return ResourceManager.GetString("lb_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 主題不能為空白 的當地語系化字串。
        /// </summary>
        public static string lb_subject_empty {
            get {
                return ResourceManager.GetString("lb_subject_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 送出報名 的當地語系化字串。
        /// </summary>
        public static string lb_submit {
            get {
                return ResourceManager.GetString("lb_submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確定送出 的當地語系化字串。
        /// </summary>
        public static string lb_submit_sure {
            get {
                return ResourceManager.GetString("lb_submit_sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請選取公司營業額 的當地語系化字串。
        /// </summary>
        public static string lb_sum_is_empty {
            get {
                return ResourceManager.GetString("lb_sum_is_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 營業額 的當地語系化字串。
        /// </summary>
        public static string lb_sumofbiz {
            get {
                return ResourceManager.GetString("lb_sumofbiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確認是否報名此活動? 的當地語系化字串。
        /// </summary>
        public static string lb_sureregister {
            get {
                return ResourceManager.GetString("lb_sureregister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 電話/分機 的當地語系化字串。
        /// </summary>
        public static string lb_tel {
            get {
                return ResourceManager.GetString("lb_tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 聯絡電話 的當地語系化字串。
        /// </summary>
        public static string lb_tel_contact {
            get {
                return ResourceManager.GetString("lb_tel_contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 電話/分機不可為空白 的當地語系化字串。
        /// </summary>
        public static string lb_telno_is_empty {
            get {
                return ResourceManager.GetString("lb_telno_is_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 職稱 的當地語系化字串。
        /// </summary>
        public static string lb_title {
            get {
                return ResourceManager.GetString("lb_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 筆數 :  的當地語系化字串。
        /// </summary>
        public static string lb_total_results {
            get {
                return ResourceManager.GetString("lb_total_results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 商洽/國際拓銷會 的當地語系化字串。
        /// </summary>
        public static string lb_tradeshow {
            get {
                return ResourceManager.GetString("lb_tradeshow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請填寫這個欄位 的當地語系化字串。
        /// </summary>
        public static string lb_typethefield {
            get {
                return ResourceManager.GetString("lb_typethefield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 報名審核中 的當地語系化字串。
        /// </summary>
        public static string lb_underreview {
            get {
                return ResourceManager.GetString("lb_underreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 未讀 的當地語系化字串。
        /// </summary>
        public static string lb_unread {
            get {
                return ResourceManager.GetString("lb_unread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 上傳失敗 的當地語系化字串。
        /// </summary>
        public static string lb_upload_fail {
            get {
                return ResourceManager.GetString("lb_upload_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 *請上傳jpg、png、gif檔案 的當地語系化字串。
        /// </summary>
        public static string lb_upload_jpg {
            get {
                return ResourceManager.GetString("lb_upload_jpg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 *請上傳pdf 檔案 的當地語系化字串。
        /// </summary>
        public static string lb_upload_pdf {
            get {
                return ResourceManager.GetString("lb_upload_pdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 上傳時間 的當地語系化字串。
        /// </summary>
        public static string lb_uploadtime {
            get {
                return ResourceManager.GetString("lb_uploadtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 目前使用量 的當地語系化字串。
        /// </summary>
        public static string lb_usedsize {
            get {
                return ResourceManager.GetString("lb_usedsize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 帳號 的當地語系化字串。
        /// </summary>
        public static string lb_user_id {
            get {
                return ResourceManager.GetString("lb_user_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 服務條款 的當地語系化字串。
        /// </summary>
        public static string lb_useragreement {
            get {
                return ResourceManager.GetString("lb_useragreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請您於三日內開啟信件，點選會員驗證連結，
        ///以完成會員註冊作業，謝謝! 的當地語系化字串。
        /// </summary>
        public static string lb_verifacationletter {
            get {
                return ResourceManager.GetString("lb_verifacationletter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 重發驗證信完成 的當地語系化字串。
        /// </summary>
        public static string lb_verifacationresent {
            get {
                return ResourceManager.GetString("lb_verifacationresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 您的會員驗證已過期，請重發驗證信或重新註冊，謝謝。 的當地語系化字串。
        /// </summary>
        public static string lb_verify_expired {
            get {
                return ResourceManager.GetString("lb_verify_expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 影音型錄 的當地語系化字串。
        /// </summary>
        public static string lb_video {
            get {
                return ResourceManager.GetString("lb_video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 影音名稱 的當地語系化字串。
        /// </summary>
        public static string lb_videoname {
            get {
                return ResourceManager.GetString("lb_videoname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 影音網址 的當地語系化字串。
        /// </summary>
        public static string lb_videosite {
            get {
                return ResourceManager.GetString("lb_videosite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 企業網址 的當地語系化字串。
        /// </summary>
        public static string lb_website {
            get {
                return ResourceManager.GetString("lb_website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 是 的當地語系化字串。
        /// </summary>
        public static string lb_yes {
            get {
                return ResourceManager.GetString("lb_yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 您可以上傳jpeg、gif、png檔案格式 的當地語系化字串。
        /// </summary>
        public static string lb_youcanupload_jpggifpng {
            get {
                return ResourceManager.GetString("lb_youcanupload_jpggifpng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 中文資訊 的當地語系化字串。
        /// </summary>
        public static string lb_zhtw_info {
            get {
                return ResourceManager.GetString("lb_zhtw_info", resourceCulture);
            }
        }
    }
}
