//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prj_BIZ_System.LanguageResource {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class User {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal User() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("prj_BIZ_System.LanguageResource.User", typeof(User).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 500萬以下 的當地語系化字串。
        /// </summary>
        public static string lb_0_5000k {
            get {
                return ResourceManager.GetString("lb_0_5000k", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 1001-1500萬 的當地語系化字串。
        /// </summary>
        public static string lb_10001_15000k {
            get {
                return ResourceManager.GetString("lb_10001_15000k", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 千元 的當地語系化字串。
        /// </summary>
        public static string lb_1000dollars {
            get {
                return ResourceManager.GetString("lb_1000dollars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 1501-3000萬 的當地語系化字串。
        /// </summary>
        public static string lb_15001k_30000k {
            get {
                return ResourceManager.GetString("lb_15001k_30000k", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 3001-5000萬 的當地語系化字串。
        /// </summary>
        public static string lb_30001k_50000k {
            get {
                return ResourceManager.GetString("lb_30001k_50000k", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 5000萬-1億 的當地語系化字串。
        /// </summary>
        public static string lb_50001k_100000k {
            get {
                return ResourceManager.GetString("lb_50001k_100000k", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 501-1000萬 的當地語系化字串。
        /// </summary>
        public static string lb_5001k_10000k {
            get {
                return ResourceManager.GetString("lb_5001k_10000k", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 關於我們 的當地語系化字串。
        /// </summary>
        public static string lb_aboutus {
            get {
                return ResourceManager.GetString("lb_aboutus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 帳號管理 的當地語系化字串。
        /// </summary>
        public static string lb_account_info {
            get {
                return ResourceManager.GetString("lb_account_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 帳號不能為空白!! 的當地語系化字串。
        /// </summary>
        public static string lb_account_is_empty {
            get {
                return ResourceManager.GetString("lb_account_is_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 帳號或密碼不能為空白!! 的當地語系化字串。
        /// </summary>
        public static string lb_accountpw_empty {
            get {
                return ResourceManager.GetString("lb_accountpw_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 帳號或密碼錯誤!! 的當地語系化字串。
        /// </summary>
        public static string lb_accountpw_wrong {
            get {
                return ResourceManager.GetString("lb_accountpw_wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 活動 的當地語系化字串。
        /// </summary>
        public static string lb_activities {
            get {
                return ResourceManager.GetString("lb_activities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 與會人數 的當地語系化字串。
        /// </summary>
        public static string lb_activity_amount {
            get {
                return ResourceManager.GetString("lb_activity_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 活動日期 的當地語系化字串。
        /// </summary>
        public static string lb_activity_date {
            get {
                return ResourceManager.GetString("lb_activity_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 活動名稱 的當地語系化字串。
        /// </summary>
        public static string lb_activity_name {
            get {
                return ResourceManager.GetString("lb_activity_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 活動編號 的當地語系化字串。
        /// </summary>
        public static string lb_activity_no {
            get {
                return ResourceManager.GetString("lb_activity_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 與會人 的當地語系化字串。
        /// </summary>
        public static string lb_activity_participant {
            get {
                return ResourceManager.GetString("lb_activity_participant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 活動期間 的當地語系化字串。
        /// </summary>
        public static string lb_activity_period {
            get {
                return ResourceManager.GetString("lb_activity_period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 活動報名 的當地語系化字串。
        /// </summary>
        public static string lb_activity_register {
            get {
                return ResourceManager.GetString("lb_activity_register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 活動地點 的當地語系化字串。
        /// </summary>
        public static string lb_activity_site {
            get {
                return ResourceManager.GetString("lb_activity_site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 活動相關資訊 的當地語系化字串。
        /// </summary>
        public static string lb_activityinfo {
            get {
                return ResourceManager.GetString("lb_activityinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 活動列表 的當地語系化字串。
        /// </summary>
        public static string lb_activitylist {
            get {
                return ResourceManager.GetString("lb_activitylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 活動註冊資訊 的當地語系化字串。
        /// </summary>
        public static string lb_activityregister {
            get {
                return ResourceManager.GetString("lb_activityregister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 活動類型 的當地語系化字串。
        /// </summary>
        public static string lb_activitytype {
            get {
                return ResourceManager.GetString("lb_activitytype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新增 的當地語系化字串。
        /// </summary>
        public static string lb_add {
            get {
                return ResourceManager.GetString("lb_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 地址 的當地語系化字串。
        /// </summary>
        public static string lb_addr {
            get {
                return ResourceManager.GetString("lb_addr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 資本額 的當地語系化字串。
        /// </summary>
        public static string lb_amountofcapital {
            get {
                return ResourceManager.GetString("lb_amountofcapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 回覆數 的當地語系化字串。
        /// </summary>
        public static string lb_amountofreply {
            get {
                return ResourceManager.GetString("lb_amountofreply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 APP下載 的當地語系化字串。
        /// </summary>
        public static string lb_appdownload {
            get {
                return ResourceManager.GetString("lb_appdownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 已完成審核 的當地語系化字串。
        /// </summary>
        public static string lb_audited {
            get {
                return ResourceManager.GetString("lb_audited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 發布人 的當地語系化字串。
        /// </summary>
        public static string lb_author {
            get {
                return ResourceManager.GetString("lb_author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 回活動報名 的當地語系化字串。
        /// </summary>
        public static string lb_back {
            get {
                return ResourceManager.GetString("lb_back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 回首頁 的當地語系化字串。
        /// </summary>
        public static string lb_backhome {
            get {
                return ResourceManager.GetString("lb_backhome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 拓銷會 的當地語系化字串。
        /// </summary>
        public static string lb_bizexploremisson {
            get {
                return ResourceManager.GetString("lb_bizexploremisson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 代表人 的當地語系化字串。
        /// </summary>
        public static string lb_boss {
            get {
                return ResourceManager.GetString("lb_boss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 買方專區 的當地語系化字串。
        /// </summary>
        public static string lb_buyerarea {
            get {
                return ResourceManager.GetString("lb_buyerarea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 買主帳號 的當地語系化字串。
        /// </summary>
        public static string lb_buyerid {
            get {
                return ResourceManager.GetString("lb_buyerid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 買主資訊 的當地語系化字串。
        /// </summary>
        public static string lb_buyerinfo {
            get {
                return ResourceManager.GetString("lb_buyerinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 買主媒合需求 的當地語系化字串。
        /// </summary>
        public static string lb_buyerneed {
            get {
                return ResourceManager.GetString("lb_buyerneed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 取消報名 的當地語系化字串。
        /// </summary>
        public static string lb_cancel {
            get {
                return ResourceManager.GetString("lb_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 上傳型錄 的當地語系化字串。
        /// </summary>
        public static string lb_catalogupload {
            get {
                return ResourceManager.GetString("lb_catalogupload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 企業類型 的當地語系化字串。
        /// </summary>
        public static string lb_category {
            get {
                return ResourceManager.GetString("lb_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 修改密碼 的當地語系化字串。
        /// </summary>
        public static string lb_changepw {
            get {
                return ResourceManager.GetString("lb_changepw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確認新密碼 的當地語系化字串。
        /// </summary>
        public static string lb_checknewpw {
            get {
                return ResourceManager.GetString("lb_checknewpw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 產業聚落列表 的當地語系化字串。
        /// </summary>
        public static string lb_cluster_list {
            get {
                return ResourceManager.GetString("lb_cluster_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 企業資料庫 的當地語系化字串。
        /// </summary>
        public static string lb_company {
            get {
                return ResourceManager.GetString("lb_company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 公司型錄 的當地語系化字串。
        /// </summary>
        public static string lb_company_catalog {
            get {
                return ResourceManager.GetString("lb_company_catalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 企業簡介 的當地語系化字串。
        /// </summary>
        public static string lb_companybrief {
            get {
                return ResourceManager.GetString("lb_companybrief", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 統一編號 的當地語系化字串。
        /// </summary>
        public static string lb_companyid {
            get {
                return ResourceManager.GetString("lb_companyid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 公司名稱 的當地語系化字串。
        /// </summary>
        public static string lb_companyname {
            get {
                return ResourceManager.GetString("lb_companyname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 想與買家洽談 的當地語系化字串。
        /// </summary>
        public static string lb_consult2buyer {
            get {
                return ResourceManager.GetString("lb_consult2buyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 想與賣家洽談 的當地語系化字串。
        /// </summary>
        public static string lb_consult2seller {
            get {
                return ResourceManager.GetString("lb_consult2seller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 主聯絡人 的當地語系化字串。
        /// </summary>
        public static string lb_contactman {
            get {
                return ResourceManager.GetString("lb_contactman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 聯絡人姓名 的當地語系化字串。
        /// </summary>
        public static string lb_contactname {
            get {
                return ResourceManager.GetString("lb_contactname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 聯絡我們 的當地語系化字串。
        /// </summary>
        public static string lb_contactus {
            get {
                return ResourceManager.GetString("lb_contactus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 版權所有 的當地語系化字串。
        /// </summary>
        public static string lb_copyright {
            get {
                return ResourceManager.GetString("lb_copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請自訂帳號 的當地語系化字串。
        /// </summary>
        public static string lb_create_account {
            get {
                return ResourceManager.GetString("lb_create_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新建活動 的當地語系化字串。
        /// </summary>
        public static string lb_create_activity {
            get {
                return ResourceManager.GetString("lb_create_activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 發佈日期 的當地語系化字串。
        /// </summary>
        public static string lb_date {
            get {
                return ResourceManager.GetString("lb_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 刪除 的當地語系化字串。
        /// </summary>
        public static string lb_delete {
            get {
                return ResourceManager.GetString("lb_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 是否確認要刪除? 的當地語系化字串。
        /// </summary>
        public static string lb_deleteornot {
            get {
                return ResourceManager.GetString("lb_deleteornot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 內容 的當地語系化字串。
        /// </summary>
        public static string lb_detail {
            get {
                return ResourceManager.GetString("lb_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 國內企業 的當地語系化字串。
        /// </summary>
        public static string lb_domestic {
            get {
                return ResourceManager.GetString("lb_domestic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 修改 的當地語系化字串。
        /// </summary>
        public static string lb_edit {
            get {
                return ResourceManager.GetString("lb_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 電子郵件 的當地語系化字串。
        /// </summary>
        public static string lb_email {
            get {
                return ResourceManager.GetString("lb_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 E-mail不可為空白 的當地語系化字串。
        /// </summary>
        public static string lb_email_is_empty {
            get {
                return ResourceManager.GetString("lb_email_is_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 英文資訊 的當地語系化字串。
        /// </summary>
        public static string lb_en_info {
            get {
                return ResourceManager.GetString("lb_en_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 業績預估表 的當地語系化字串。
        /// </summary>
        public static string lb_estimate {
            get {
                return ResourceManager.GetString("lb_estimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 說明 的當地語系化字串。
        /// </summary>
        public static string lb_explain {
            get {
                return ResourceManager.GetString("lb_explain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 常見問題 的當地語系化字串。
        /// </summary>
        public static string lb_faqs {
            get {
                return ResourceManager.GetString("lb_faqs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 外國企業 的當地語系化字串。
        /// </summary>
        public static string lb_foreign {
            get {
                return ResourceManager.GetString("lb_foreign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 忘記密碼 的當地語系化字串。
        /// </summary>
        public static string lb_forget_pw {
            get {
                return ResourceManager.GetString("lb_forget_pw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 推薦活動 的當地語系化字串。
        /// </summary>
        public static string lb_good_activities {
            get {
                return ResourceManager.GetString("lb_good_activities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 首頁 的當地語系化字串。
        /// </summary>
        public static string lb_home {
            get {
                return ResourceManager.GetString("lb_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 編號 的當地語系化字串。
        /// </summary>
        public static string lb_id {
            get {
                return ResourceManager.GetString("lb_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 若您忘記密碼，請輸入註冊時的帳號及Email，系統將送一組預設密碼給您，如有疑問，請洽系統管理人員，謝謝。 的當地語系化字串。
        /// </summary>
        public static string lb_ifforgetpw {
            get {
                return ResourceManager.GetString("lb_ifforgetpw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 企業資料說明 的當地語系化字串。
        /// </summary>
        public static string lb_info {
            get {
                return ResourceManager.GetString("lb_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 最新活動 的當地語系化字串。
        /// </summary>
        public static string lb_latest_activity {
            get {
                return ResourceManager.GetString("lb_latest_activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 最新消息 的當地語系化字串。
        /// </summary>
        public static string lb_latest_activitynews {
            get {
                return ResourceManager.GetString("lb_latest_activitynews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 最新上架企業 的當地語系化字串。
        /// </summary>
        public static string lb_latest_company {
            get {
                return ResourceManager.GetString("lb_latest_company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 最新新聞 的當地語系化字串。
        /// </summary>
        public static string lb_latest_news {
            get {
                return ResourceManager.GetString("lb_latest_news", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 最新影音型錄 的當地語系化字串。
        /// </summary>
        public static string lb_latest_video {
            get {
                return ResourceManager.GetString("lb_latest_video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 最新型錄 的當地語系化字串。
        /// </summary>
        public static string lb_latestcatalog {
            get {
                return ResourceManager.GetString("lb_latestcatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 相關資訊連結 的當地語系化字串。
        /// </summary>
        public static string lb_link {
            get {
                return ResourceManager.GetString("lb_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 會員登入 的當地語系化字串。
        /// </summary>
        public static string lb_login {
            get {
                return ResourceManager.GetString("lb_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 上傳LOGO 的當地語系化字串。
        /// </summary>
        public static string lb_logoupload {
            get {
                return ResourceManager.GetString("lb_logoupload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 登出 的當地語系化字串。
        /// </summary>
        public static string lb_logout {
            get {
                return ResourceManager.GetString("lb_logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 操作手冊 的當地語系化字串。
        /// </summary>
        public static string lb_manual {
            get {
                return ResourceManager.GetString("lb_manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 商務媒合 的當地語系化字串。
        /// </summary>
        public static string lb_matchmaking {
            get {
                return ResourceManager.GetString("lb_matchmaking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 一億以上 的當地語系化字串。
        /// </summary>
        public static string lb_morethan100000k {
            get {
                return ResourceManager.GetString("lb_morethan100000k", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 聚落訊息 的當地語系化字串。
        /// </summary>
        public static string lb_msg_cluster {
            get {
                return ResourceManager.GetString("lb_msg_cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 公司訊息 的當地語系化字串。
        /// </summary>
        public static string lb_msg_company {
            get {
                return ResourceManager.GetString("lb_msg_company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 訊息管理 的當地語系化字串。
        /// </summary>
        public static string lb_msg_managment {
            get {
                return ResourceManager.GetString("lb_msg_managment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 私人訊息 的當地語系化字串。
        /// </summary>
        public static string lb_msg_private {
            get {
                return ResourceManager.GetString("lb_msg_private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 可複選 的當地語系化字串。
        /// </summary>
        public static string lb_multiple {
            get {
                return ResourceManager.GetString("lb_multiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 必須為 的當地語系化字串。
        /// </summary>
        public static string lb_must {
            get {
                return ResourceManager.GetString("lb_must", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 我的資料庫 的當地語系化字串。
        /// </summary>
        public static string lb_mycompany {
            get {
                return ResourceManager.GetString("lb_mycompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 我的會員資料 的當地語系化字串。
        /// </summary>
        public static string lb_myinfo {
            get {
                return ResourceManager.GetString("lb_myinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 創建新帳號 的當地語系化字串。
        /// </summary>
        public static string lb_newid {
            get {
                return ResourceManager.GetString("lb_newid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新密碼 的當地語系化字串。
        /// </summary>
        public static string lb_newpw {
            get {
                return ResourceManager.GetString("lb_newpw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新聞 的當地語系化字串。
        /// </summary>
        public static string lb_news {
            get {
                return ResourceManager.GetString("lb_news", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 否 的當地語系化字串。
        /// </summary>
        public static string lb_no {
            get {
                return ResourceManager.GetString("lb_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 目前沒有推薦的活動 的當地語系化字串。
        /// </summary>
        public static string lb_no_recommended {
            get {
                return ResourceManager.GetString("lb_no_recommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 您尚未參加任何活動 的當地語系化字串。
        /// </summary>
        public static string lb_no_register {
            get {
                return ResourceManager.GetString("lb_no_register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 查無資料!! 的當地語系化字串。
        /// </summary>
        public static string lb_nodata {
            get {
                return ResourceManager.GetString("lb_nodata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 未選擇任何檔案 的當地語系化字串。
        /// </summary>
        public static string lb_nonefile {
            get {
                return ResourceManager.GetString("lb_nonefile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 訂單列表 的當地語系化字串。
        /// </summary>
        public static string lb_order_list {
            get {
                return ResourceManager.GetString("lb_order_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 主辦單位 的當地語系化字串。
        /// </summary>
        public static string lb_organizer {
            get {
                return ResourceManager.GetString("lb_organizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 舊密碼 的當地語系化字串。
        /// </summary>
        public static string lb_originalpw {
            get {
                return ResourceManager.GetString("lb_originalpw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 密碼 的當地語系化字串。
        /// </summary>
        public static string lb_password {
            get {
                return ResourceManager.GetString("lb_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 線上型錄 的當地語系化字串。
        /// </summary>
        public static string lb_pdf {
            get {
                return ResourceManager.GetString("lb_pdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 上傳檔案 的當地語系化字串。
        /// </summary>
        public static string lb_pdfupload {
            get {
                return ResourceManager.GetString("lb_pdfupload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 業績管理 的當地語系化字串。
        /// </summary>
        public static string lb_performance {
            get {
                return ResourceManager.GetString("lb_performance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 手機號碼 的當地語系化字串。
        /// </summary>
        public static string lb_phone_no {
            get {
                return ResourceManager.GetString("lb_phone_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 上傳小圖 的當地語系化字串。
        /// </summary>
        public static string lb_photoupload {
            get {
                return ResourceManager.GetString("lb_photoupload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請用統一編號註冊 的當地語系化字串。
        /// </summary>
        public static string lb_pleaseuse_companyid {
            get {
                return ResourceManager.GetString("lb_pleaseuse_companyid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 隱私政策 的當地語系化字串。
        /// </summary>
        public static string lb_privacypolicy {
            get {
                return ResourceManager.GetString("lb_privacypolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 公司產品 的當地語系化字串。
        /// </summary>
        public static string lb_product_company {
            get {
                return ResourceManager.GetString("lb_product_company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 產品說明 的當地語系化字串。
        /// </summary>
        public static string lb_product_info {
            get {
                return ResourceManager.GetString("lb_product_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 產品名稱 的當地語系化字串。
        /// </summary>
        public static string lb_product_name {
            get {
                return ResourceManager.GetString("lb_product_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 公司簡介 的當地語系化字串。
        /// </summary>
        public static string lb_profile {
            get {
                return ResourceManager.GetString("lb_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 密碼不能為空白!! 的當地語系化字串。
        /// </summary>
        public static string lb_pw_is_empty {
            get {
                return ResourceManager.GetString("lb_pw_is_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 密碼請設8個字元的英文及數字混合 的當地語系化字串。
        /// </summary>
        public static string lb_pwset8 {
            get {
                return ResourceManager.GetString("lb_pwset8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 報價單列表 的當地語系化字串。
        /// </summary>
        public static string lb_quotation_list {
            get {
                return ResourceManager.GetString("lb_quotation_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 同上密碼請再次輸入確認 的當地語系化字串。
        /// </summary>
        public static string lb_reenterpw {
            get {
                return ResourceManager.GetString("lb_reenterpw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 報名資料 的當地語系化字串。
        /// </summary>
        public static string lb_registerinfo {
            get {
                return ResourceManager.GetString("lb_registerinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 業務帳號列表 的當地語系化字串。
        /// </summary>
        public static string lb_sales_idlist {
            get {
                return ResourceManager.GetString("lb_sales_idlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 儲存 的當地語系化字串。
        /// </summary>
        public static string lb_save {
            get {
                return ResourceManager.GetString("lb_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 產業別 的當地語系化字串。
        /// </summary>
        public static string lb_scope {
            get {
                return ResourceManager.GetString("lb_scope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請選擇產業別 的當地語系化字串。
        /// </summary>
        public static string lb_scope_sel {
            get {
                return ResourceManager.GetString("lb_scope_sel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 搜尋 的當地語系化字串。
        /// </summary>
        public static string lb_search {
            get {
                return ResourceManager.GetString("lb_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 搜尋結果 的當地語系化字串。
        /// </summary>
        public static string lb_searchresult {
            get {
                return ResourceManager.GetString("lb_searchresult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Logo圖片選擇成功 的當地語系化字串。
        /// </summary>
        public static string lb_select_successful {
            get {
                return ResourceManager.GetString("lb_select_successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 賣家帳號 的當地語系化字串。
        /// </summary>
        public static string lb_sellerid {
            get {
                return ResourceManager.GetString("lb_sellerid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 賣家清單 的當地語系化字串。
        /// </summary>
        public static string lb_sellerlist {
            get {
                return ResourceManager.GetString("lb_sellerlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 註冊 的當地語系化字串。
        /// </summary>
        public static string lb_signup {
            get {
                return ResourceManager.GetString("lb_signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 我要報名 的當地語系化字串。
        /// </summary>
        public static string lb_signup_me {
            get {
                return ResourceManager.GetString("lb_signup_me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 主題 的當地語系化字串。
        /// </summary>
        public static string lb_subject {
            get {
                return ResourceManager.GetString("lb_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 送出報名 的當地語系化字串。
        /// </summary>
        public static string lb_submit {
            get {
                return ResourceManager.GetString("lb_submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確定送出 的當地語系化字串。
        /// </summary>
        public static string lb_submit_sure {
            get {
                return ResourceManager.GetString("lb_submit_sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 營業額 的當地語系化字串。
        /// </summary>
        public static string lb_sumofbiz {
            get {
                return ResourceManager.GetString("lb_sumofbiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 電話/分機 的當地語系化字串。
        /// </summary>
        public static string lb_tel {
            get {
                return ResourceManager.GetString("lb_tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 聯絡電話 的當地語系化字串。
        /// </summary>
        public static string lb_tel_contact {
            get {
                return ResourceManager.GetString("lb_tel_contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 職稱 的當地語系化字串。
        /// </summary>
        public static string lb_title {
            get {
                return ResourceManager.GetString("lb_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 筆數 :  的當地語系化字串。
        /// </summary>
        public static string lb_total_results {
            get {
                return ResourceManager.GetString("lb_total_results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 商洽會 的當地語系化字串。
        /// </summary>
        public static string lb_tradeshow {
            get {
                return ResourceManager.GetString("lb_tradeshow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請填寫這個欄位 的當地語系化字串。
        /// </summary>
        public static string lb_typethefield {
            get {
                return ResourceManager.GetString("lb_typethefield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 報名審核中 的當地語系化字串。
        /// </summary>
        public static string lb_underreview {
            get {
                return ResourceManager.GetString("lb_underreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 帳號 的當地語系化字串。
        /// </summary>
        public static string lb_user_id {
            get {
                return ResourceManager.GetString("lb_user_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 服務條款 的當地語系化字串。
        /// </summary>
        public static string lb_useragreement {
            get {
                return ResourceManager.GetString("lb_useragreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 影音型錄 的當地語系化字串。
        /// </summary>
        public static string lb_video {
            get {
                return ResourceManager.GetString("lb_video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 影音名稱 的當地語系化字串。
        /// </summary>
        public static string lb_videoname {
            get {
                return ResourceManager.GetString("lb_videoname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 影音網址 的當地語系化字串。
        /// </summary>
        public static string lb_videosite {
            get {
                return ResourceManager.GetString("lb_videosite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 企業網址 的當地語系化字串。
        /// </summary>
        public static string lb_website {
            get {
                return ResourceManager.GetString("lb_website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 是 的當地語系化字串。
        /// </summary>
        public static string lb_yes {
            get {
                return ResourceManager.GetString("lb_yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 您可以上傳jpeg、gif、png檔案格式 的當地語系化字串。
        /// </summary>
        public static string lb_youcanupload_jpggifpng {
            get {
                return ResourceManager.GetString("lb_youcanupload_jpggifpng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 中文資訊 的當地語系化字串。
        /// </summary>
        public static string lb_zhtw_info {
            get {
                return ResourceManager.GetString("lb_zhtw_info", resourceCulture);
            }
        }
    }
}
